"""Composable builders for the global LSQR constraint blocks.

These are the constraint rows appended in the parent process *after* the data
rows (per-frame adjacency / polynomial constraints are emitted inside the
worker and are not built by these helpers). Each builder returns a :class:`ConstraintBlock`
(or ``None`` when it would be empty); ``setup_lsqr`` appends them in a fixed
order that the CSR scatter depends on:

    1. per-map mean-offset anchors (one per chunk map)
    2. sky damping, in sky-component order (continuum, then each line block)
    3. offset damping

Bit-identity contract: the exact cols/data/b values, dtypes, and nnz_per_row
emitted here are frozen by the byte-equality regression goldens (reference
``cal_*.h5`` files generated by ``selfcal_scripts/benchmarks/regress_cal.py`` /
``regress_cal_spectral.py``, diffed with
``selfcal_scripts/drivers/diff_cal_h5.py``); re-baseline those before changing
any of them. ``sky_damping_block`` damps every sky component uniformly: block
``j`` lives at columns ``j*num_sky + valid_pixels`` with
``data = sqrt(weight * coverage)`` (block 0 = continuum, blocks 1+ = line
components).
"""
from dataclasses import dataclass

import numpy as np


@dataclass
class ConstraintBlock:
    """One global constraint block. Mirrors the dict the CSR scatter consumes."""

    rows_local: np.ndarray
    cols: np.ndarray
    data: np.ndarray
    b: np.ndarray
    num_rows: int
    nnz_per_row: object  # int (uniform) or ndarray (per-row)

    def as_dict(self):
        return {
            'rows_local': self.rows_local,
            'cols': self.cols,
            'data': self.data,
            'b': self.b,
            'num_rows': self.num_rows,
            'nnz_per_row': self.nnz_per_row,
        }


def mean_offset_block(m, mean_off, num_frames, num_chunks_m, ftg_m, col_bases,
                      weight=10.0):
    """Per-frame mean-offset anchor for chunk map ``m``.

    Constrains each frame's per-chunk offset mean toward ``mean_off`` (length
    num_frames) with the given Lagrange ``weight``. Caller must skip template-
    mode maps (no per-chunk offsets) and None ``mean_off``.
    """
    mean_offsets_arr = np.asarray(mean_off)
    nc_m = num_chunks_m
    rows_local = np.repeat(np.arange(num_frames, dtype=np.int64), nc_m)
    offset_starts = col_bases[m] + ftg_m.astype(np.int64) * nc_m
    cols = (offset_starts[:, None] + np.arange(nc_m, dtype=np.int64)[None, :]).reshape(-1)
    data = np.full(num_frames * nc_m, weight, dtype=np.float32)
    b = mean_offsets_arr.astype(np.float64).flatten() * nc_m * weight
    return ConstraintBlock(rows_local, cols, data, b, num_rows=num_frames, nnz_per_row=nc_m)


def sky_damping_block(block_index, weight, coverage, num_sky):
    """Coverage-weighted Tikhonov damping for sky block ``block_index``.

    block 0 = continuum, block 1+ = line components. Columns are
    ``block_index*num_sky + valid_pixels``; one nnz per damped pixel with
    ``data = sqrt(weight * coverage[pixel])``. Returns None if no covered pixel.
    """
    valid = np.nonzero(coverage)[0]
    if len(valid) == 0:
        return None
    data = np.sqrt(weight * coverage[valid]).astype(np.float32)
    n = len(valid)
    cols = (block_index * num_sky + valid).astype(np.int64, copy=False)
    return ConstraintBlock(np.arange(n, dtype=np.int64), cols, data,
                           np.zeros(n, dtype=np.float64), num_rows=n, nnz_per_row=1)


def offset_damping_block(weight, offset_block_coverage, num_sky_eff):
    """Coverage-weighted damping on the offset columns (``damp_offset``).

    Columns are ``num_sky_eff + valid_offset_cols``. Returns None if empty.
    """
    valid = np.nonzero(offset_block_coverage)[0]
    if len(valid) == 0:
        return None
    data = np.sqrt(weight * offset_block_coverage[valid]).astype(np.float32)
    n = len(valid)
    cols = (valid + num_sky_eff).astype(np.int64, copy=False)
    return ConstraintBlock(np.arange(n, dtype=np.int64), cols, data,
                           np.zeros(n, dtype=np.float64), num_rows=n, nnz_per_row=1)
