"""Line-profile models for the spectral sky components.

A :class:`LineProfile` maps per-observation wavelengths (and optional auxiliary
maps) to a dimensionless line-shape coefficient ``G`` (peak ≈ 1 at line center).
The LSQR row for a spectral component multiplies the pixel weight by ``G`` (see
:mod:`selfcal.models.sky_model` and the row assembly in
:mod:`selfcal.core.assembly`).

Bit-identity contract (SPHEREx PAH 3.29 µm): the original inline computation
in ``selfcal.core.assembly._prep_lsqr`` for the per-pixel Gaussian was::

    obs_sigma_per = sub_BW[valid] / 2.355
    sigma_per     = np.sqrt(obs_sigma_per * obs_sigma_per + 2.890e-4)
    G_per         = np.exp(-0.5 * ((lambda_per - line_center) / sigma_per) ** 2).astype(np.float32)

``QuadratureSigma`` and ``GaussianProfile`` reproduce that exact sequence
(same op order, same float32 cast timing). The two literals — ``2.355``
(FWHM→σ) and ``2.890e-4`` (PAH intrinsic σ², which is NOT exactly
``PAH_INTRINSIC_SIGMA_UM**2``) — are carried verbatim. Do not "fix" them
without re-baselining the byte-equality regression goldens (reference
``cal_*.h5`` outputs generated by ``selfcal_scripts/benchmarks/regress_cal*.py``
and compared with ``selfcal_scripts/drivers/diff_cal_h5.py``).
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

__all__ = [
    'QuadratureSigma',
    'SpectralProfile',
    'LineProfile',
    'GaussianProfile',
    'LinearProfile',
    'TemplateProfile',
]


@dataclass(frozen=True)
class QuadratureSigma:
    """Per-pixel Gaussian σ from an instrument LSF width map ⊗ an intrinsic width.

    ``σ(pixel) = sqrt((aux[fwhm_key] / fwhm_to_sigma)**2 + intrinsic_var_um2)``.

    For SPHEREx PAH this is ``QuadratureSigma(fwhm_key='BW', fwhm_to_sigma=2.355,
    intrinsic_var_um2=2.890e-4)`` and reproduces the legacy expression exactly.
    """

    fwhm_key: str = 'BW'
    fwhm_to_sigma: float = 2.355
    intrinsic_var_um2: float = 0.0

    def evaluate(self, aux: dict[str, np.ndarray]) -> np.ndarray:
        """Per-pixel Gaussian σ from the LSF width map and intrinsic width.

        Parameters
        ----------
        aux : dict[str, np.ndarray]
            Auxiliary maps at the valid pixels; must contain ``fwhm_key`` (the
            instrument LSF-width map).

        Returns
        -------
        np.ndarray
            The per-pixel σ ``sqrt((aux[fwhm_key]/fwhm_to_sigma)**2 +
            intrinsic_var_um2)``.
        """
        obs = aux[self.fwhm_key] / self.fwhm_to_sigma
        return np.sqrt(obs * obs + self.intrinsic_var_um2)


class SpectralProfile:
    """Base class / duck-typed protocol for an arbitrary spectral shape.

    ``evaluate(lam_um, aux) -> float32 ndarray`` returns the dimensionless
    per-observation coefficient (template value) at each wavelength. The shape
    can be any analytical form or numerical template; it is NOT line-specific.
    The owning :class:`~selfcal.models.sky_model.SpectralComponent` solves the per-pixel
    amplitude that multiplies this shape.
    """

    #: aux-map keys this profile samples (besides the wavelength key the
    #: owning component supplies). Used to declare SHM aux requirements.
    aux_requirements: tuple = ()

    def evaluate(self, lam_um: np.ndarray, aux: dict[str, np.ndarray]) -> np.ndarray:  # pragma: no cover - interface
        """Dimensionless spectral coefficient at each observation wavelength.

        Parameters
        ----------
        lam_um : np.ndarray
            Per-observation wavelengths in µm.
        aux : dict[str, np.ndarray]
            Auxiliary maps at the valid pixels, keyed by aux-map name (the keys
            listed in ``aux_requirements``).

        Returns
        -------
        np.ndarray
            The float32 per-observation coefficient (template value).
        """
        raise NotImplementedError


# Back-compat alias (the abstraction is general, not line-specific).
LineProfile = SpectralProfile


@dataclass(frozen=True)
class GaussianProfile(SpectralProfile):
    """Gaussian shape ``exp(-0.5 * ((λ - center)/σ)**2)`` (analytical template).

    ``σ`` is per-pixel from ``sigma_source`` (a :class:`QuadratureSigma`) when
    its width map is available in ``aux``; otherwise the scalar ``sigma_um``
    fallback is used. Preserving this fallback order (per-pixel width map when
    present, scalar σ otherwise) is part of the bit-identity contract described
    in the module docstring.
    """

    center_um: float
    sigma_um: float = None
    sigma_source: QuadratureSigma = None

    @property
    def aux_requirements(self) -> tuple[str, ...]:
        """Aux-map keys sampled: the width-map key when ``sigma_source`` is set."""
        if self.sigma_source is not None:
            return (self.sigma_source.fwhm_key,)
        return ()

    def evaluate(self, lam_um: np.ndarray, aux: dict[str, np.ndarray]) -> np.ndarray:
        """Gaussian coefficient ``exp(-0.5 * ((λ - center)/σ)**2)``.

        Parameters
        ----------
        lam_um : np.ndarray
            Per-observation wavelengths in µm.
        aux : dict[str, np.ndarray]
            Auxiliary maps at the valid pixels; supplies ``sigma_source``'s
            width map when present (else the scalar ``sigma_um`` fallback runs).

        Returns
        -------
        np.ndarray
            The float32 per-observation Gaussian coefficient.
        """
        if (self.sigma_source is not None
                and aux.get(self.sigma_source.fwhm_key) is not None):
            sigma = self.sigma_source.evaluate(aux)
        else:
            sigma = self.sigma_um
        return np.exp(-0.5 * ((lam_um - self.center_um) / sigma) ** 2).astype(np.float32)


@dataclass(frozen=True)
class LinearProfile(SpectralProfile):
    """Normalized linear ramp ``t = (λ − center_um) / halfwidth_um``.

    The coefficient of a spectrally-SLOPED continuum block: sky(P, λ) =
    cont0[P] + cont_slope[P]·t(λ). ``t`` spans [-1, 1] over the fit window when
    ``halfwidth_um`` is the window half-width, so cont_slope is in the same
    units as cont0 (amplitude at the window edge). Not clipped — mildly
    extrapolates outside the window.
    """

    center_um: float
    halfwidth_um: float

    aux_requirements: tuple = ()

    def evaluate(self, lam_um: np.ndarray, aux: dict[str, np.ndarray]) -> np.ndarray:
        """Normalized linear ramp ``t = (λ - center_um) / halfwidth_um``.

        Parameters
        ----------
        lam_um : np.ndarray
            Per-observation wavelengths in µm.
        aux : dict[str, np.ndarray]
            Auxiliary maps at the valid pixels (unused; the ramp needs none).

        Returns
        -------
        np.ndarray
            The float32 per-observation ramp value (not clipped to [-1, 1]).
        """
        return ((np.asarray(lam_um, dtype=np.float64) - self.center_um)
                / self.halfwidth_um).astype(np.float32)


@dataclass(frozen=True)
class TemplateProfile(SpectralProfile):
    """Arbitrary numerical template: linear interpolation of tabulated
    ``(wave_um, values)``.

    Zero outside the tabulated range. Demonstrates that the profile interface is
    not Gaussian- or line-specific — any tabulated spectral shape works; a
    Gaussian-sampled template matches GaussianProfile to float32 precision
    (see ``tests/test_sky_model.py::test_template_profile_matches_interp_and_gaussian``).
    """

    wave_um: np.ndarray
    values: np.ndarray

    aux_requirements: tuple = ()

    def evaluate(self, lam_um: np.ndarray, aux: dict[str, np.ndarray]) -> np.ndarray:
        """Linear interpolation of the tabulated ``(wave_um, values)`` template.

        Parameters
        ----------
        lam_um : np.ndarray
            Per-observation wavelengths in µm.
        aux : dict[str, np.ndarray]
            Auxiliary maps at the valid pixels (unused; the template needs none).

        Returns
        -------
        np.ndarray
            The float32 interpolated template value, zero outside the tabulated
            wavelength range.
        """
        return np.interp(lam_um, self.wave_um, self.values,
                         left=0.0, right=0.0).astype(np.float32)
